spring:
  application:
    name: springai-mcp-client
  ai:
    chat:
        client:
            enabled: true
    mcp:
      client:
        enabled: true
        name: spring-ai-mcp-client
        version: 1.0.0
        request-timeout: 60s
        type: sync
        sse:
          connections:
            mcp-server:
              url: http://localhost:8080/
    openai:
      api-key: ${OPENAI_API_KEY:}




server:
  port: 8081
  servlet:
    context-path: /springai-mcp-client